matrix:
  include:
    - language: php
      php: 7.1.3
      before_script:
        - cp .env.travis .env
        - mysql -e 'create database homestead_test;'
        - composer self-update
        - composer install --no-interaction
        - php artisan key:generate
        - php artisan migrate
      script: vendor/bin/phpunit
    - language: node_js
      node_js: "9"

notifications:
  email:
    recipients:
      - moorlagrx@gmail.com
      - moorlagt@gmail.com
    on_success: never
    on_failure: always 