matrix:
  include:
    - language: php
      php: 7.1.3
      before_script:
        - cp .env.example .env
        - composer self-update
        - composer install --no-interaction
      script: vendor/bin/phpunit
    - language: node_js
      node_js: "9"

notifications:
  email:
    recipients:
      - moorlagrx@gmail.com
      - moorlagt@gmail.com
    on_success: never
    on_failure: always 